# -*- coding: utf-8 -*-
"""Vlink_Q1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FfGv2me8D-9a5cD8TxO6bBJ18I3SuJWA
"""

n=int(input("Enter the no. of Words:"))
lst = []
if n > 0:
  for i in range (n+1):
    lst.append(input("Enter the elements:"))
  lst.sort(key = len)
  print(lst)
else:
  print("Invalid Input")